name: Login CI
# Run login/logout tests

on:
  workflow_run:
    workflows: [ "Pywikibot CI" ]
    branches: [ master ]
    types:
      - completed

env:
  PYWIKIBOT_TEST_RUNNING: 1
  PYWIKIBOT_USERNAME: Pywikibot-test
  PYWIKIBOT_LOGIN_LOGOUT: 1

jobs:
  build:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    timeout-minutes: 2

    strategy:
      fail-fast: 
